const { schema, normalize } = require('normalizr')
const data = [
  {
    id: 326,
    parent: {
      id: 199,
      gender: 'unisex',
      name: 'Beauty',
      slug: 'beauty',
      type: 'product',
      is_featured: false,
    },
    gender: 'unisex',
    name: 'Fragrance',
    slug: 'beauty-fragrance',
    type: 'product',
    is_featured: false,
  },
  {
    id: 200,
    parent: {
      id: 199,
      gender: 'unisex',
      name: 'Beauty',
      slug: 'beauty',
      type: 'product',
      is_featured: false,
    },
    gender: 'unisex',
    name: 'Make Up',
    slug: 'beauty-make-up',
    type: 'product',
    is_featured: false,
    children: [
      {
        id: 213,
        gender: 'unisex',
        name: 'Eyes',
        slug: 'make-up-eyes',
        type: 'product',
        is_featured: false,
        children: [
          {
            id: 215,
            gender: 'unisex',
            name: 'Eye Shadow',
            slug: 'eyes-eye-shadow',
            type: 'product',
            is_featured: false,
          },
          {
            id: 216,
            gender: 'unisex',
            name: 'Eye Primer',
            slug: 'eyes-eye-primer',
            type: 'product',
            is_featured: false,
          },
          {
            id: 217,
            gender: 'unisex',
            name: 'Eye Lash Glue',
            slug: 'eyes-eye-lash-glue',
            type: 'product',
            is_featured: false,
          },
          {
            id: 218,
            gender: 'unisex',
            name: 'False Eyelashes',
            slug: 'eyes-false-eyelashes',
            type: 'product',
            is_featured: false,
          },
          {
            id: 221,
            gender: 'unisex',
            name: 'Eye Palette',
            slug: 'eyes-eye-palette',
            type: 'product',
            is_featured: false,
          },
          {
            id: 222,
            gender: 'unisex',
            name: 'Eye Set',
            slug: 'eyes-eye-set',
            type: 'product',
            is_featured: false,
          },
          {
            id: 214,
            gender: 'unisex',
            name: 'Eyeliner',
            slug: 'eyes-eyeliner',
            type: 'product',
            is_featured: false,
          },
          {
            id: 219,
            gender: 'unisex',
            name: 'Mascara',
            slug: 'eyes-mascara',
            type: 'product',
            is_featured: false,
          },
          {
            id: 220,
            gender: 'unisex',
            name: 'Under Eye Concealer',
            slug: 'eyes-under-eye-concealer',
            type: 'product',
            is_featured: false,
          },
        ],
      },
      {
        id: 223,
        gender: 'unisex',
        name: 'Lips',
        slug: 'make-up-lips',
        type: 'product',
        is_featured: false,
        children: [
          {
            id: 224,
            gender: 'unisex',
            name: 'Lipstick',
            slug: 'lips-lipstick',
            type: 'product',
            is_featured: false,
          },
          {
            id: 227,
            gender: 'unisex',
            name: 'Lip Balm',
            slug: 'lips-lip-balm',
            type: 'product',
            is_featured: false,
          },
          {
            id: 229,
            gender: 'unisex',
            name: 'Lip Stain & Tint',
            slug: 'lips-lip-stain-and-tint',
            type: 'product',
            is_featured: false,
          },
          {
            id: 230,
            gender: 'unisex',
            name: 'Lip Liner',
            slug: 'lips-lip-liner',
            type: 'product',
            is_featured: false,
          },
          {
            id: 231,
            gender: 'unisex',
            name: 'Lip Palette & Sets',
            slug: 'lips-lip-palette-and-sets',
            type: 'product',
            is_featured: false,
          },
          {
            id: 232,
            gender: 'unisex',
            name: 'Lip Scrub',
            slug: 'lips-lip-scrub',
            type: 'product',
            is_featured: false,
          },
          {
            id: 225,
            gender: 'unisex',
            name: 'Lip Gloss',
            slug: 'lips-lip-gloss',
            type: 'product',
            is_featured: false,
          },
          {
            id: 226,
            gender: 'unisex',
            name: 'Lip Crayon',
            slug: 'lips-lip-crayon',
            type: 'product',
            is_featured: false,
          },
          {
            id: 228,
            gender: 'unisex',
            name: 'Lip Primer',
            slug: 'lips-lip-primer',
            type: 'product',
            is_featured: false,
          },
        ],
      },
      {
        id: 233,
        gender: 'unisex',
        name: 'Brow',
        slug: 'make-up-brow',
        type: 'product',
        is_featured: false,
        children: [
          {
            id: 234,
            gender: 'unisex',
            name: 'Brow Pencil',
            slug: 'brow-brow-pencil',
            type: 'product',
            is_featured: false,
          },
          {
            id: 235,
            gender: 'unisex',
            name: 'Brow Kit',
            slug: 'brow-brow-kit',
            type: 'product',
            is_featured: false,
          },
          {
            id: 236,
            gender: 'unisex',
            name: 'Brow Gel',
            slug: 'brow-brow-gel',
            type: 'product',
            is_featured: false,
          },
        ],
      },
      {
        id: 237,
        gender: 'unisex',
        name: 'Brushes & Applicator',
        slug: 'make-up-brushes-and-applicator',
        type: 'product',
        is_featured: false,
        children: [
          {
            id: 238,
            gender: 'unisex',
            name: 'Face Brushes',
            slug: 'brushes-and-applicator-face-brushes',
            type: 'product',
            is_featured: false,
          },
          {
            id: 239,
            gender: 'unisex',
            name: 'Eye Brushes',
            slug: 'brushes-and-applicator-eye-brushes',
            type: 'product',
            is_featured: false,
          },
          {
            id: 240,
            gender: 'unisex',
            name: 'Lip Brushes',
            slug: 'brushes-and-applicator-lip-brushes',
            type: 'product',
            is_featured: false,
          },
          {
            id: 241,
            gender: 'unisex',
            name: 'Multi Use',
            slug: 'brushes-and-applicator-multi-use',
            type: 'product',
            is_featured: false,
          },
          {
            id: 242,
            gender: 'unisex',
            name: 'Sponge & Beauty Blender',
            slug: 'brushes-and-applicator-sponge-and-beauty-blender',
            type: 'product',
            is_featured: false,
          },
          {
            id: 243,
            gender: 'unisex',
            name: 'Brush Cleaner',
            slug: 'brushes-and-applicator-brush-cleaner',
            type: 'product',
            is_featured: false,
          },
          {
            id: 244,
            gender: 'unisex',
            name: 'Brush Set',
            slug: 'brushes-and-applicator-brush-set',
            type: 'product',
            is_featured: false,
          },
        ],
      },
      {
        id: 245,
        gender: 'unisex',
        name: 'Tools & Accessories',
        slug: 'make-up-tools-and-accessories',
        type: 'product',
        is_featured: false,
        children: [
          {
            id: 246,
            gender: 'unisex',
            name: 'Eyelash Curler',
            slug: 'tools-and-accessories-eyelash-curler',
            type: 'product',
            is_featured: false,
          },
          {
            id: 247,
            gender: 'unisex',
            name: 'Tweezers',
            slug: 'tools-and-accessories-tweezers',
            type: 'product',
            is_featured: false,
          },
          {
            id: 248,
            gender: 'unisex',
            name: 'Sharpener',
            slug: 'tools-and-accessories-sharpener',
            type: 'product',
            is_featured: false,
          },
        ],
      },
      {
        id: 201,
        gender: 'unisex',
        name: 'Face',
        slug: 'make-up-face',
        type: 'product',
        is_featured: false,
        children: [
          {
            id: 203,
            gender: 'unisex',
            name: 'Blush',
            slug: 'face-blush',
            type: 'product',
            is_featured: false,
          },
          {
            id: 206,
            gender: 'unisex',
            name: 'Contour',
            slug: 'face-contour',
            type: 'product',
            is_featured: false,
          },
          {
            id: 208,
            gender: 'unisex',
            name: 'Highlighter & Illuminator',
            slug: 'face-highlighter-and-illuminator',
            type: 'product',
            is_featured: false,
          },
          {
            id: 209,
            gender: 'unisex',
            name: 'Powder',
            slug: 'face-powder',
            type: 'product',
            is_featured: false,
          },
          {
            id: 202,
            gender: 'unisex',
            name: 'BB & CC Cream',
            slug: 'face-bb-and-cc-cream',
            type: 'product',
            is_featured: false,
          },
          {
            id: 205,
            gender: 'unisex',
            name: 'Concealer&Corrector',
            slug: 'face-concealerandcorrector',
            type: 'product',
            is_featured: false,
          },
          {
            id: 207,
            gender: 'unisex',
            name: 'Foundation',
            slug: 'face-foundation',
            type: 'product',
            is_featured: false,
          },
          {
            id: 210,
            gender: 'unisex',
            name: 'Primer',
            slug: 'face-primer',
            type: 'product',
            is_featured: false,
          },
          {
            id: 211,
            gender: 'unisex',
            name: 'Setting & Finishing Spray',
            slug: 'face-setting-and-finishing-spray',
            type: 'product',
            is_featured: false,
          },
          {
            id: 212,
            gender: 'unisex',
            name: 'Tinted Moisturizer',
            slug: 'face-tinted-moisturizer',
            type: 'product',
            is_featured: false,
          },
          {
            id: 204,
            gender: 'unisex',
            name: 'Bronzer',
            slug: 'face-bronzer',
            type: 'product',
            is_featured: false,
          },
        ],
      },
    ],
  },
  {
    id: 132,
    parent: {
      id: 38,
      parent: {
        id: 37,
        gender: 'unisex',
        name: 'Fashion',
        slug: 'fashion',
        type: 'product',
        is_featured: false,
      },
      gender: 'unisex',
      name: "Women's Clothing",
      slug: 'fashion-womens-clothing',
      type: 'product',
      is_featured: false,
    },
    gender: 'unisex',
    name: 'Shoes',
    slug: 'womens-clothing-shoes',
    type: 'product',
    is_featured: false,
    children: [
      {
        id: 134,
        gender: 'unisex',
        name: 'Heels&Pumps',
        slug: 'shoes-heelsandpumps',
        type: 'product',
        is_featured: false,
        children: [
          {
            id: 135,
            gender: 'unisex',
            name: 'Mid-Low Heels',
            slug: 'heelsandpumps-mid-low-heels',
            type: 'product',
            is_featured: false,
          },
          {
            id: 136,
            gender: 'unisex',
            name: 'High Heels',
            slug: 'heelsandpumps-high-heels',
            type: 'product',
            is_featured: false,
          },
        ],
      },
      {
        id: 138,
        gender: 'unisex',
        name: 'Wedges',
        slug: 'shoes-wedges',
        type: 'product',
        is_featured: false,
      },
      {
        id: 140,
        gender: 'unisex',
        name: 'Boots',
        slug: 'shoes-boots',
        type: 'product',
        is_featured: false,
      },
      {
        id: 143,
        gender: 'unisex',
        name: 'Socks',
        slug: 'shoes-socks',
        type: 'product',
        is_featured: false,
      },
      {
        id: 142,
        gender: 'unisex',
        name: 'Sport Shoes',
        slug: 'shoes-sport-shoes',
        type: 'product',
        is_featured: false,
      },
      {
        id: 133,
        gender: 'unisex',
        name: 'Flats',
        slug: 'shoes-flats',
        type: 'product',
        is_featured: false,
      },
      {
        id: 137,
        gender: 'unisex',
        name: 'Sandal',
        slug: 'shoes-sandal',
        type: 'product',
        is_featured: false,
      },
      {
        id: 139,
        gender: 'unisex',
        name: 'Mules',
        slug: 'shoes-mules',
        type: 'product',
        is_featured: false,
      },
      {
        id: 141,
        gender: 'unisex',
        name: 'Sneakers',
        slug: 'shoes-sneakers',
        type: 'product',
        is_featured: false,
      },
    ],
  },
]

const grandchildrenCategory = new schema.Entity('category')

const childrenCategory = new schema.Entity('category', {
  children: [new schema.Entity('category')],
})

const category = new schema.Entity(
  'category',
  {
    children: [childrenCategory],
  },
  {
    processStrategy: entity => {
      entity.data = entity.children
      return entity
    },
  },
)

const normalizeData = normalize(data, [category])

Object.keys(normalizeData).map(key => console.log(normalizeData[key]))
